// <auto-generated />
using System;
using BlackSlope.Repositories.Movies.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BlackSlope.Api.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BlackSlope.Repositories.Movies.DtoModels.MovieDtoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasName("IX_Movies_Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, ut consul soluta persius quo, et eam mundi scribentur, eros invidunt dissentias no eum.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 854, DateTimeKind.Local).AddTicks(3677),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Eos dolor perpetua ne, cum agam causae petentium ei.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7863),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "At idque electram moderatius vix. Legere postulant at per.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7911),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sanctus fuisset pericula cu usu, mea an idque dicam accumsan.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7917),
                            Title = "The Godfather: Part II"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Et natum tollit sed.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7920),
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Usu ad omnium civibus persecuti.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7924),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Description = "In graeco omnesque oporteat vim, ad sed nonumy consulatu.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7928),
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Odio euismod et vel, has ad modo graecis pertinacia.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7931),
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vim nibh solet scaevola te, sea illud posse partem an.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7934),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ad mea errem legimus efficiendi.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7937),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Sale dolorum fabellas te cum, cu sea purto civibus menandri.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7940),
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Idque viris zril vel et.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7943),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ius ut luptatum democritum ullamcorper. Dolor possit facilis sit an, sit ei rebum meliore interesset.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7947),
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Cum meliore admodum ei, eos id summo audire, qui facilisi deterruisset ei.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7950),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Vix ei falli salutatus eloquentiam.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7953),
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Congue verear consetetur pri at.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7956),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ius eu sapientem constituam, aeque assueverit his ea, in homero graeco saperet quo.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7959),
                            Title = "Goodfellas"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Et est vero animal torquatos, illum principes eum ad, ad vocent iisque fuisset qui.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7962),
                            Title = "Star Wars: Episode V - The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Has vocent fastidii appareat ne, mel eu fabellas scripserit.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7965),
                            Title = "One Flew Over the Cuckoo's Nest"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Et duo iudico semper fabulas.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7968),
                            Title = "Seven Samurai"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Eos te volumus interesset, sint cotidieque eum et.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7972),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Ad vel graece principes definitiones, ad vide populo vis, ex eos sumo efficiantur necessitatibus.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7975),
                            Title = "City of God"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Mel an sumo iusto, clita facilis adipiscing cum cu.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7979),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Has vocent alienum te.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7982),
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Eu adhuc percipit eleifend eam.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7985),
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Clita mollis disputando cu eam, no pri insolens abhorreant.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7988),
                            Title = "Life Is Beautiful "
                        },
                        new
                        {
                            Id = 27,
                            Description = "Ex atomorum repudiandae has, euismod vocibus ei eam, ei eam esse pertinacia abhorreant.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7991),
                            Title = "The Usual Suspects"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Et probo ornatus sententiae cum, in unum urbanitas usu.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(7994),
                            Title = "Se7en"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Velit omittam inciderint te cum, sit at urbanitas reformidans.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8062),
                            Title = "Léon: The Professional"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Causae tincidunt pro no, ius munere viderer albucius ex.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8066),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Id detraxit facilisi eleifend mea, mel ex nobis bonorum oporteat, ius oportere evertitur ut.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8069),
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id = 32,
                            Description = "No discere adolescens mnesarchum eam, quo latine voluptua ei.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8072),
                            Title = "It's a Wonderful Life"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ei pro dolorem fierent blandit, te mea viris nihil legimus.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8075),
                            Title = "Once Upon a Time ... in Hollywood"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Ex duo euismod fastidii, cu euismod splendide signiferumque qui, eu eos doctus virtute.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8078),
                            Title = "Spider-Man: Into the Spider-Verse"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Eum cu quem integre verterem, has animal fabulas ut.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8081),
                            Title = "Avengers: Infinity War"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Tacimates definiebas has an.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8085),
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Nec ut ridens meliore pertinax.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8088),
                            Title = "The Intouchables"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Mei te graeci essent, dico sapientem cum ea, eum ei graeci alterum.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8091),
                            Title = "The Prestige"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Elit quando dictas eos ei.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8095),
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Eros tota utinam mei ei, iisque consequuntur te his.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8098),
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Ne per fugit graece, quando expetendis id sea.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8101),
                            Title = "Memento"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Duo novum noluisse et, at vel adhuc porro minim.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8104),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Dictas contentiones no his, exerci oportere ea eam.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8108),
                            Title = "American History X"
                        },
                        new
                        {
                            Id = 44,
                            Description = "No sonet omnes mnesarchum quo.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8111),
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Postea platonem has te, ei quod dicit sit, sea et movet delicata scribentur.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8114),
                            Title = "Terminator 2: Judgment Day"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Malis dictas detracto et ius, no qualisque vulputate per.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8117),
                            Title = "Cinema Paradiso"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Platonem oportere in has, nam recusabo delicata elaboraret ei, dico gubergren hendrerit ex sea.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8120),
                            Title = "Grave of the Fireflies"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Cu usu velit omittam temporibus, natum vulputate sea eu.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8126),
                            Title = "Back to the Future"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Gubergren scriptorem eu vel, eius percipitur te per, vel tale habeo et.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8129),
                            Title = "Raiders of the Lost Ark"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Alii insolens inciderint pro an, ei eos utinam commodo tacimates.",
                            ReleaseDate = new DateTime(2020, 2, 14, 10, 2, 44, 857, DateTimeKind.Local).AddTicks(8132),
                            Title = "Apocalypse Now"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
